# -*- coding: utf-8 -*-
"""Aula01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUg14BV4ZWfYTFIKvASraR5hMJ8voBRL

##**Aula 01: Introdução ao processamento de imagens**

###Cabeçalho de práticamente todos os códigos:
"""

# Commented out IPython magic to ensure Python compatibility.
from io import IncrementalNewlineDecoder
# Importando bibliotecas
import cv2
import numpy as np

# Imprimindo gráficos:
# %matplotlib inline
from matplotlib import pyplot as plt

"""###Imprimindo a versão"""

print("OpenCV Versão: %s" %cv2.__version__)

"""###Exibindo Imagens"""

image = cv2.imread("NATUREZA_1.jpg")

plt.imshow(image)

"""###Para não exibir eixos nas imagens"""

image = cv2.imread("NATUREZA_1.jpg")
plt.imshow(image)
plt.axis('off')
plt.show()

"""###Correção de cor -> BGR 2 RGB"""

image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.imshow(image_rgb)

plt.axis('off')
plt.show()

"""#### Mostrando a representação interna da imagem -> SHAPE:"""

print("SHAPE:")
print("Dimensões da imagem:", image_rgb.shape)
print("Quantidade de linhas:", image_rgb.shape[0])
print("Quantidade de colunas:", image_rgb.shape[1])
print("Camadas de cores:", image_rgb.shape[2])

"""### Mostrando a representação interna da imagem -> MATRIZ:"""

print("MATRIZ:")
print("Dimensões da imagem: \n", image_rgb)

"""### Desafio 01"""

# Importando a imagem:
image3x3 = cv2.imread("img3x3.png")

# Shape da imagem:
print("Dimensões da imagem:", image3x3.shape)

# Matriz da Imagem:
print("\nMatriz da imagem:\n", image3x3)

# Imagem:
plt.imshow(cv2.cvtColor(image3x3, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.show()

"""###Carregando a imagem na versão tons de cinza:"""

image3x3cinza = cv2.imread("img3x3.png", cv2.IMREAD_GRAYSCALE)

# OU:
# Use o argumento 0:
#image3x3cinza = cv2.imread("img3x3.png", 0)

plt.imshow(image3x3cinza)
plt.axis('off')
plt.show()
image3x3cinza

"""### Desafio 02:"""

# Correção para os tons de cinza:

# O carregamento da imagem é igual
image3x3cinza = cv2.imread("img3x3.png", cv2.IMREAD_GRAYSCALE)

# Para exibir a imagem corretamente:
plt.imshow(image3x3cinza, cmap="gray")  # Definir o mapa de cores como escala de cinza
plt.axis('off')
plt.show()

"""### Alterando o tamanho de uma imagem"""

# Carregando a imagem na versão colorida de um arquivo
image = cv2.imread("NATUREZA_1.jpg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

print("Dimensões da imagem: ", image.shape)

imagem2 = cv2.resize(image, (600,400), cv2.INTER_LINEAR)

print("Novas dimensões da imagem: ", imagem2.shape)

plt.imshow(imagem2)
plt.show()

"""#### Desafio 03"""

# Carregar a imagem
image3x3 = cv2.imread("img3x3.png")

# Modificar o pixel (0,0) para Magenta (BGR: 255,0,255)
image3x3[0, 0] = [255, 0, 255]  # OpenCV usa ordem BGR

# Exibir a imagem modificada
plt.imshow(cv2.cvtColor(image3x3, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.show()